# Generated by Django 2.2.6 on 2020-01-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
