# Generated by Django 2.2.6 on 2020-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gravatar_url',
            field=models.URLField(max_length=255),
        ),
    ]
