# Generated by Django 2.2.6 on 2020-01-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0008_auto_20200123_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
