# Generated by Django 2.2.6 on 2020-01-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0009_remove_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lead',
        ),
    ]
