# Generated by Django 2.2.6 on 2020-02-03 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0017_auto_20200203_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(max_length=255),
        ),
    ]
