# Generated by Django 2.2.6 on 2020-02-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0018_auto_20200203_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
