# Generated by Django 2.2.6 on 2020-02-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0020_auto_20200208_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='looking_for',
            field=models.TextField(),
        ),
    ]
