# Generated by Django 2.2.6 on 2020-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprojects', '0021_auto_20200208_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
